### ISSUE TITLE
RabbitMQ/epmd binding to IPv4 address broken in Trusty

### ISSUE THREAD

**Issue by jerenkrantz** [bloomberg/bcpc#377]
We are attempting to run RabbitMQ and bind it to a specific IPv4 address. This fails with Trusty. 

This appears to be a duplicate of: 

https://bugs.launchpad.net/ubuntu/+source/erlang/+bug/1374109

and perhaps related to:

https://bugs.launchpad.net/ubuntu/+source/rabbitmq-server/+bug/1312507?comments=all 

A quick reproduction recipe: 

```
root@bcpc-vm1:~# apt-cache policy erlang-base 
erlang-base: 
Installed: 1:16.b.3-dfsg-1ubuntu2.1 
Candidate: 1:16.b.3-dfsg-1ubuntu2.1 
Version table: 
*** 1:16.b.3-dfsg-1ubuntu2.1 0 
500 http://10.0.100.4/ubuntu/ trusty-updates/main amd64 Packages 
100 /var/lib/dpkg/status 
1:16.b.3-dfsg-1ubuntu2 0 
500 http://10.0.100.4/ubuntu/ trusty/main amd64 Packages 
root@bcpc-vm1:~# export ERL_EPMD_ADDRESS=127.0.1.1 
root@bcpc-vm1:~# epmd -d 
epmd: Fri Nov 7 21:09:42 2014: epmd running - daemon = 0 
epmd: Fri Nov 7 21:09:42 2014: cannot parse IP address "127.0.1.1"
root@bcpc-vm1:~#
```

Removing ERL_EPMD_ADDRESS from the bcpc.conf template is a potential workaround, but means epmd isn't accessible remotely.  This may break RabbitMQ clustering.  =(

Upstream ticket filed with Canonical.

**Comment by kamidzi** [comment]
I don't think this is a concern anymore?
