### ISSUE TITLE
Pinning versions of major components 

### ISSUE THREAD

**Issue by caiush** [bloomberg/bcpc#523]
BCPC is tested with particular versions. The recent rabbitmq release broke our build. We should pin the following components:
* Mysql
* Rabbitmq
* Ceph

And possibly Openstack components.

**Comment by kamidzi** [comment]
Attempting this is not without its perils as well. See #579

**Comment by erhudy** [comment]
Certain mirrors that like to remove older versions of packages are highly problematic here; Erlang and RabbitMQ both stand out as offenders, since they remove the older versions from their repos as soon as a newer patch release drops.

**Comment by erhudy** [comment]
Add the HAProxy PPA to that list.
