### ISSUE TITLE
Allow users to update instance metadata by default

### ISSUE THREAD

**Issue by jerenkrantz** [bloomberg/bcpc#753]
BOSH (via fog Ruby gem) requires updating the instance metadata to pass along information to the agent on the guest.  I think that it makes sense to permit users to do so as they see fit.

(Otherwise, a policy exception will occur if not run by a site admin.)

The following patch to `attributes.rb` suffices:

```
@@ -564,6 +564,8 @@ default['bcpc']['nova']['policy'] = {
   "compute:delete" => "rule:admin_or_owner",
   "compute:unlock_override" => "rule:admin_api",
 
+  "compute:update_instance_metadata" => "rule:admin_or_owner",
+
   "compute:get_rdp_console" => "rule:admin_or_owner",
   "compute:get_vnc_console" => "rule:admin_or_owner",
```

**Comment by dkaplan34** [comment]
In addition to update instance metadata, the following two policy additions are needed to delete metadata 
  "compute:get_instance_metadata": "rule:admin_or_owner",
  "compute:delete_instance_metadata": "rule:admin_or_owner",
